### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [rocky/python-decompile3#69]
## Description
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

## Background
Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
[Markus_Elfring@fedora lokal]$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/decompile3/lokal -name '*.py')
```

How do you think about to improve eight source code places? :thinking:

**Comment by rocky** [comment]
You have a weird and annoying way of expressing what you want, because of vagueness.  Basically this request is that you want it easier for some tool to look at this code and that analysis code somehow finds it easier with augmented assignment statements. Users of the code are otherwise not really helped.  In the Python Fascism world though I suppose some would argue that writing ` x += j` instead of `x = x + j` make the the code easier to read (which personally I don't buy). 

So be it though. Addressed in your PR.

**Comment by elfring** [comment]
>… that you want it easier for some tool to look at this code and that analysis code somehow finds it easier with augmented assignment statements.

I find that you interpret my change proposal in a questionable direction. :thinking:
I am just trying again to point further possibilities out for another bit of collateral evolution.
